### PR TITLE
Add language, product tag, and storage configuration.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
@andrenatal can you take a look at this when you have a chance?

**Comment by mrstegeman** [comment]
@andrenatal can you take a look at this when you have a chance?

**Review by andrenatal — APPROVED** [review]

**Comment by mrstegeman** [comment]
Thanks. Feel free to merge, as I don't have permission.

**Comment by autonome** [comment]
@mrstegeman howdy! can you add a test to the file in /tests to pass these new options in? Fine if it is just simple test passing the defaults - want to make sure that code path is executed at least.

**Comment by mrstegeman** [comment]
@autonome Done.

**Comment by autonome** [comment]
👍🏼👍🏼👍🏼 thanks!

**Pull request merged**
